name: Python application
on:
 # schedule:
  #  - cron: '7 12 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install
      run: |
        pip install -r requirements.txt
    - name: Scrape
      env:
        HOST: ${{ secrets.HOST }}
        FTP_USER: ${{ secrets.FTP_USER }}
        PASSWORD: ${{ secrets.PASSWORD }}
      run: |
        python health_breach_scrape.py
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Update: ${timestamp}" || exit 0
        git push
